### PR TITLE
Speed enhancement and refactor

### PR DESCRIPTION
**Pull request by Radexito**
I've removed delay in favor of synchronous calls (much much faster)
I've optimized four for loops into one (the mode nodes the more speed difference)
general refactor, added typing and docstrings.
Added a method to integrate into nuke.

### CODE REVIEW

**Comment by herronelou** [comment]
Does removing the delay actually work? What you have now is what I had at first, but every now and then some tiles would come all black or mangled, particularly for users with slower machines. Slowing things down was the only way we found with these users to prevent misfiring.

**Comment by Radexito** [comment]
> Does removing the delay actually work?

It works for me, but I tested this on a pretty fast machine (xenon E5-1650 v3, Quadro RTX4000)

> but every now and then some tiles would come all black or mangled, particularly for users with slower machines. Slowing things down was the only way we found with these users to prevent misfiring.

I haven't encountered those issues after refactoring the code.

I've noticed I made two errors, corrected them.

**Comment by herronelou** [comment]
Good to know that you didn't run into issues without using the delay.
Just because we had so many issues without a delay in the past I'm hesitant to fully remove it.
Do you think you can leave it but have it be optional? I don't have a slow PC to test with anymore I upgraded last year.

**Comment by Radexito** [comment]
I've brought back the delay, and set it to 0 by default.
I formatted using ruff and updated screen shot to reflect latest version.

**Comment by herronelou** [comment]
Thanks for the work. I've made a tag 1.0.0 for what was the current version which will be the last to be py2 compatible.

**Pull request merged**
